server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/szs
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true # print
        format_sql: true

szs:
  security:
    # HS512 64byte
    # echo 'jarvis-and-villains-a-service-that-makes-you-a-great-hero-access-token'|base64
    access-token-issuer: amFydmlzLWFuZC12aWxsYWlucy1hLXNlcnZpY2UtdGhhdC1tYWtlcy15b3UtYS1ncmVhdC1oZXJvLWFjY2Vzcy10b2tlbgo=
    access-token-expiration: PT12H

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace